alias work='cd ~/Workspace'
alias act='source venv/bin/activate'
alias deact='deactivate'
alias djrun='python manage.py runserver'
alias djmm='python manage.py makemigrations'
alias djmg='python manage.py migrate'
alias djtest='python manage.py test'
alias delpyc='find . -name "*.pyc" -delete'
alias ls='ls -G'
alias l='ls -laG'
alias grep='grep --color=auto'
alias sy09='cd ~/Workspace/sy09/'
